[package]
name = "rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.20", features = ["full"]}
tokio-core = "0.1.17"
tokio-io = "0.1.13"
tempfile = "3.1.0"
